### PR TITLE
Replace grpc/metadata's NewContext and FromContext calls with appropriate Incoming/Outgoing versions

### LINKED ISSUE #624: gRPC metadata.NewContext and metadata.FromContext should not be used
After some recent changes in grpc-go, `metadata.NewContext` now assumes you are accessing the _outgoing_ metadata, and `metadata.FromContext` assumes you are retrieving the _incoming_ credentials.  We are planning on removing these functions due to this ambiguity and the fact that the behavior was changed to avoid unintentional forwarding of metadata when a server makes outgoing grpc calls.

For more information, please see:

https://github.com/grpc/grpc-go/issues/1219
https://github.com/grpc/proposal/pull/25
https://groups.google.com/forum/#!topic/grpc-io/-qM_UnYFHJs

### PR DESCRIPTION
**Pull request by dfawley**
Fixes #624

### CODE REVIEW

**Comment by dfawley** [comment]
Is there some way to re-run the tests for this change?  The failure happened during `go install` without any error message, so I'm hoping it will pass if it's retried.

**Comment by rakyll** [comment]
We use Gerrit for code reviews and kokoro for CI, do you want me to resubmit this commit via Gerrit?

**Comment by rakyll** [comment]
You can also follow the instructions at https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/CONTRIBUTING.md to create a CL.

**Comment by dfawley** [comment]
I moved this over to Gerrit.  Thanks for the pointer.

**Pull request closed without merging**
