### PR TITLE
Adding timestamp range filter to big table

### PR DESCRIPTION
**Pull request by bbassingthwaite-va**

### CODE REVIEW

**Comment by garye** [comment]
Thanks! We use gerrit for code reviews, check out the instructions here:
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/CONTRIBUTING.md

Can you submit a PR over there?

**Comment by bbassingthwaite-va** [comment]
Will do, thanks!

**Comment by bbassingthwaite-va** [comment]
I signed it! 

https://code-review.googlesource.com/#/c/8810/

**Comment by rakyll** [comment]
Closed the PR in favor of the Gerrit CL.

**Pull request closed without merging**
