### PR TITLE
spanner: don't recycle session if it was never initialized

### PR DESCRIPTION
**Pull request by jeffizhungry**

### CODE REVIEW

**Comment by jeffizhungry** [comment]
I signed it!

**Comment by vkedia** [comment]
Thanks for sending this. But this repo is a mirror of the original repo so you need to make this change there. This document has instructions on that:
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/CONTRIBUTING.md

**Comment by jeffizhungry** [comment]
@vkedia I submitted a review https://code-review.googlesource.com/#/c/12830/
But there are issues with the build. Could I get some assistance? 😄

**Comment by jeffizhungry** [comment]
@vkedia Did you get a chance to review this?

**Comment by rakyll** [comment]
I am closing this, please continue the discussion at https://code-review.googlesource.com/#/c/12830/.

**Pull request closed without merging**
