### PR TITLE
Update query.go

### PR DESCRIPTION
**Pull request by danielfs**

### CODE REVIEW

**Comment by danielfs** [comment]
I signed it!

**Comment by jadekler** [comment]
Hi @danielfs - thanks for your contribution! We'd love to review it but unfortunately, although we're working on getting a bot to help us accept contributions from github, we currently only use Gerrit. Would you mind submitting this change there?

You can follow the instructions for getting set up listed in our [`CONTRIBUTING.md`](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/CONTRIBUTING.md).

**Comment by danielfs** [comment]
@jadekler Error when deploying to Appengine:

`ERROR: (gcloud.app.deploy) Error Response: [9] Deployment contains files that cannot be compiled: Compile failed:
/work_dir/cloud.google.com/go/bigquery/query.go:165: cannot use true (type bool) as type *bool in assignment
/work_dir/cloud.google.com/go/bigquery/query.go:167: cannot use false (type bool) as type *bool in assignment
/work_dir/cloud.google.com/go/bigquery/query.go:198: cannot use qq.UseLegacySql (type *bool) as type bool in field value
/work_dir/cloud.google.com/go/bigquery/query.go:199: invalid operation: ! *bool
2018/04/25 09:24:23 go-app-builder: build timing: 127\xd7compile (1m14.576s total), 0\xd7link (0s total)
2018/04/25 09:24:23 go-app-builder: failed running compile: exit status 2`

**Comment by jadekler** [comment]
ping @jba

**Comment by jba** [comment]
You have to update both google.golang.org/api/bigquery/v2 and cloud.google.com/go/bigquery to head.

**Pull request closed without merging**
