### PR TITLE
Fix bug in documentation

### PR DESCRIPTION
**Pull request by antoniojrod**
Add the missing useLogging parameter

### CODE REVIEW

**Comment by jba** [comment]
Thanks for contributing! If you don't want to go through the paperwork, I can just make this change for you.

**Comment by antoniojrod** [comment]
I tried to fill in the paperwork, but I just get:

A server error occurred, please try your request again.

So I don't know if I can report that bug somewhere.  You can go ahead and
make the change yourself since it just doesn't seem like Google wants to
cooperate with me.  :P

**Comment by jba** [comment]
Sorry about that!

**Comment by jba** [comment]
Fix is in. Thanks again, closing this now.

**Pull request closed without merging**
