### PR TITLE
Stackdriver product rename

### PR DESCRIPTION
**Pull request by tmatsuo**
Renaming some APIs to Stackdriver brand

### CODE REVIEW

**Comment by jba** [comment]
We don't accept pull requests because we use gerrit, but I will take care of this.

**Comment by jba** [comment]
Actually, @pongad, this is on you (it's in the generated logging client).

**Comment by tmatsuo** [comment]
Thanks, sometimes I run an automated script which grep and replace strings like this. Do you want me to blacklist this repo, or is a PR like this still a good reminder so that I can continue creating such PRs?

**Comment by jba** [comment]
Keep doing what you're doing, and we'll adjust.

**Comment by rakyll** [comment]
Sorry, we use gerrit for code reviews, check out the instructions here:
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/CONTRIBUTING.md

Can you create a Gerrit CL by following the steps there?

**Comment by pongad** [comment]
This should have been fixed by https://code-review.googlesource.com/#/c/8850/ . Can we verify and close this?

**Comment by jba** [comment]
Verified.

**Pull request closed without merging**
