### PR TITLE
Fix unreachable code

### PR DESCRIPTION
**Pull request by Bankq**
go tool vet complains.

### CODE REVIEW

**Comment by Bankq** [comment]
I signed it!

**Comment by Bankq** [comment]
Hmm integration test failed but I'm not sure it's relevant. Can someone advise?

**Comment by Bankq** [comment]
ping

**Comment by pongad** [comment]
I'm sorry we didn't get to this. This repo uses Gerrit codereview tool, not GitHub PRs (though we use GitHub issue tracker). Could you please recreate this PR on Gerrit? ([Instructions here](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/CONTRIBUTING.md#contributing))

**Comment by Bankq** [comment]
Sure!
Thanks!

**Comment by Bankq** [comment]
gerrit tracking here: https://code-review.googlesource.com/#/c/12630/

**Comment by pongad** [comment]
Thank you @Bankq !

**Pull request closed without merging**
